export const projects = [
  {
    id: 5,
    title: "Lessora AI",
    subtitle: "AI-Powered Lesson Planning Platform",
    description:
      "An AI lesson planning platform for K-12 teachers. Pick a topic, grade level, and learning objective, then it generates a complete, curriculum-aligned lesson plan you can use straight in class and no account required. Built as a Next.js 15 monolith with MongoDB for storage. Powered by the OpenAI API, with daily AI credits for anonymous sessions, session-based history, DOC/PDF export, admin dashboard, and usage tracking.",
    tech: ["Next.js", "TypeScript", "MongoDB", "OpenAI API", "Resend"],
    demoLink: "https://lessora.ajgenabio.me/",
    linkLabel: "View Live Site",
    year: "2026",
    role: "Fullstack Developer",
    category: "featured",
  },
  {
    id: 1,
    title: "PSITS Website",
    subtitle: "Student Organization Management & E-Commerce Platform",
    description:
      "The official website for PSITS, a student org with 3,000+ members in the College of Computer Studies at UC. Handles merchandise sales, uniform orders, event signups, attendance, and POS for in-person transactions. Before this, everything was done through Google Forms and manual spreadsheets.",
    tech: ["React", "Node.js", "Express", "AWS S3", "Tailwind CSS"],
    demoLink: "https://psits.org/",
    year: "2024",
    role: "Lead Developer",
    category: "featured",
  },
  {
    id: 6,
    title: "Noetix",
    subtitle: "Persona-aware AI decision service",
    description:
      "Decides what an AI should be and how it should behave for a given data payload. Sends persona + goal + data; gets structured natural-language responses with traceable guardrail matches. 16 personas, session-based state, OpenAI API.",
    tech: ["Node.js", "OpenAI API", "TypeScript"],
    demoLink: "#",
    linkLabel: "View Documentation",
    year: "2026",
    role: "AI Orchestrator / Founder",
    category: "featured",
  },
  {
    id: 7,
    title: "Archiona",
    subtitle: "Persona-gated pre-coding workflow for AI agents",
    description:
      "A CLI tool that makes coding agents plan before they write code. Scaffolds .archiona/, creates reviewable plans, decomposes goals into persona-gated tasks, and auto-injects the active persona skill into each agent's instruction file via `archiona hook`. Eight-phase workflow: evidence, design, tests, approval, build, validate, review, with a 15-persona registry (pm, researcher, architect, developer, qa, reviewer, security, etc.) and skills the agent follows instead of its own defaults. Wires into opencode, Cursor, Cline, Copilot, Continue, Codex, and Aider.",
    tech: ["Node.js", "TypeScript", "npm CLI", "Markdown"],
    demoLink: "#",
    linkLabel: "View on npm",
    year: "2026",
    role: "AI Workflow / Founder",
    category: "featured",
  },
  {
    id: 8,
    title: "Kinora AI",
    subtitle: "Personal video + image studio",
    description:
      "Write a prompt, press record, get cinematic output. Video up to 60s/4K, image generation, prompt refinement, wallpaper mode with anime auto-modifiers, mood board with A/B comparison. Built with Next.js 16, Tailwind v4, and the Agnes AI API.",
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    demoLink: "",
    linkLabel: "",
    year: "2026",
    role: "Fullstack Developer / Founder",
    category: "featured",
  },
  {
    id: 2,
    title: "MentalHelp PH",
    subtitle: "Capstone - therapist matching",
    description:
      "A platform that connects people in the Philippines with therapists who fit their needs. Users answer a questionnaire and get matched with professionals. Built this as my capstone project because I kept seeing people struggle to find affordable mental health support.",
    tech: ["React", "Express", "Node.js", "XAMPP", "SQL"],
    demoLink: "#",
    year: "2024",
    role: "Fullstack developer",
    category: "school",
  },
];
