export const projects = [
  {
    id: 5,
    title: "Lessora AI",
    subtitle: "AI-Powered Lesson Planning Platform",
    description:
      "An AI lesson planning tool for teachers. Pick a topic, grade level, and learning objective, then it generates a structured lesson plan you can use straight in class. Built with Expo React Native for mobile, Node.js + Express for the backend, and MongoDB for storage. Uses the OpenAI API to generate plans, with login, dashboards, and usage tracking.",
    tech: [
      "TypeScript",
      "Expo",
      "React Native",
      "Node.js",
      "Express",
      "MongoDB",
      "OpenAI API",
    ],
    demoLink: "https://lessora-ai.ajgenabio.me/",
    linkLabel: "View Live Site",
    year: "2026",
    role: "Fullstack Developer",
    category: "featured",
  },
  {
    id: 1,
    title: "PSITS Website",
    subtitle: "Student Organization Management & E-Commerce Platform",
    description:
      "The official website for PSITS, a student org with 3,000+ members in the College of Computer Studies at UC. Handles merchandise sales, uniform orders, event signups, attendance, and POS for in-person transactions. Before this, everything was done through Google Forms and manual spreadsheets.",
    tech: ["React", "Node.js", "Express", "AWS S3", "Tailwind CSS"],
    demoLink: "https://psits.org/",
    year: "2024",
    role: "Lead Developer",
    category: "featured",
  },
  {
    id: 6,
    title: "Noetix",
    subtitle: "Persona-aware AI decision service",
    description:
      "Decides what an AI should be and how it should behave for a given data payload. Sends persona + goal + data; gets structured natural-language responses with traceable guardrail matches. 16 personas, session-based state, OpenAI API.",
    tech: ["Node.js", "OpenAI API", "TypeScript"],
    demoLink: "#",
    linkLabel: "View Documentation",
    year: "2026",
    role: "AI Orchestrator / Founder",
    category: "featured",
  },
  {
    id: 7,
    title: "Archiona",
    subtitle: "Pre-coding gate CLI tool",
    description:
      "A CLI tool that makes coding agents plan before they write code. Scaffolds .archiona/, creates reviewable plans, seeds skills, and wires into opencode/Cursor/Cline/Copilot. Approve the plan, then it codes.",
    tech: ["Node.js", "TypeScript", "npm CLI"],
    demoLink: "#",
    linkLabel: "View on npm",
    year: "2026",
    role: "Creator / Founder",
    category: "featured",
  },
  {
    id: 8,
    title: "Kinora AI",
    subtitle: "Personal video + image studio",
    description:
      "Write a prompt, press record, get cinematic output. Video up to 60s/4K, image generation, prompt refinement, wallpaper mode with anime auto-modifiers, mood board with A/B comparison. Built with Next.js 16, Tailwind v4, and the Agnes AI API.",
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    demoLink: "",
    linkLabel: "",
    year: "2026",
    role: "Fullstack Developer / Founder",
    category: "featured",
  },
  {
    id: 2,
    title: "MentalHelp PH",
    subtitle: "Capstone - therapist matching",
    description:
      "A platform that connects people in the Philippines with therapists who fit their needs. Users answer a questionnaire and get matched with professionals. Built this as my capstone project because I kept seeing people struggle to find affordable mental health support.",
    tech: ["React", "Express", "Node.js", "XAMPP", "SQL"],
    demoLink: "#",
    year: "2024",
    role: "Fullstack developer",
    category: "school",
  },
];
